name: Deploy to Cloud Run

on:
  push:
    branches:
      - develop
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/berx3-front-dev:$GITHUB_SHA .

      - name: Push Docker image to GCR
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/berx3-front-dev:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy berx3-front-dev \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/berx3-front-dev:$GITHUB_SHA \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --quiet
